### ISSUE TITLE
Roles as playbooks

### ISSUE THREAD

**Issue by ajdelgado** [DHDcc/archlinux-ansible#1]
https://github.com/DHDcc/archlinux-ansible/blob/6e7a5c4febcd6f90d48ca49b0715db8f0620a43a/ansible/playbook.yml#L11
Hi, I saw in the Fediverse https://mastodon.social/@devops_discussions/113178589145649675 that you were asking for feedback. Here is some from someone that has been working with Ansible the last 5 years or so.
You seem to be using roles as playbooks. It works but not really how I would do it.
Roles are meant to be shareable between repositories (you can use the requirements.txt in Ansible to define them pointing to another repo so you can use someone's else role to configure a mail server for example).
Most of your roles seem to be parts of your configuration (like 'presetup'), maybe this should have been a whole role, that then you can use in different Ansible environments. I have similar role (private) for configuring the default user I want in my computers/servers that creates and configure users, clone repos I use, install tools I use, etc.
Also you are here using "json-style" definitions with "yaml-style" ones, I would try to be consistent and keep using the YAML way. Again it works, but it's less readable.
Ping me in https://eu.mastodon.green/@adelgado if you want more help with Ansible (or Puppet)

**Comment by DHDcc** [comment]
Hi @ajdelgado, thanks for your feedback. I'm working on it .

**Comment by DHDcc** [comment]
61c229c21a49b790db3447655937084ffdbae17a

**Comment by DHDcc** [comment]
3514f6754d6bcf33ec4f12f3f6efaedcbd05e047

**Comment by DHDcc** [comment]
88e9682c029f8b0f106580b6b03305e663291625
